var submitProgress=false;glsPontok='';mmjQuery=jQuery.noConflict();mmjQuery(window).load(function(){var parent_url=decodeURIComponent(document.location.hash.replace(/^#/,'')),link;var error=false;var emailuniquefail=false;var emailuniquecheck=false;var checkNum=0;function setHeight(extraHeight){try{messaging.postMessage({if_height:parseInt(mmjQuery.getDocHeight())+extraHeight,form_id:105130},parent_url,parent);if(mmjQuery("#mssysform1051301478628143 input[name='mssys_referer_page']").length==0){mmjQuery("#mssysform1051301478628143").append('<input type="hidden" name="mssys_referer_page" value="'+parent_url+'">');}}catch(err){}};mmjQuery(".mezo983375").hide();mmjQuery("#mmform-container1478628143 .submitbutton").click(function(e){vatCheck=false;mmjQuery(this).addClass('mm-submit-disabled');if(mmjQuery(this).attr('id')=='want_upsell'){mmjQuery("#mssysform1051301478628143 input[name='mssys_want_upsell']").val('1');}else if(mmjQuery(this).attr('id')=='dont_want_upsell'){mmjQuery("#mssysform1051301478628143 input[name='mssys_want_upsell']").val('0');}
mmjQuery("#mssysform1051301478628143").trigger('submit');});if(mmjQuery("#mmform-container1478628143 .postalsamechk").length>0){if(mmjQuery("#mmform-container1478628143 .postalsamechk").is(":checked")){mmjQuery("#mmform-container1478628143 div[id^='containermssys_postal_']").hide();}}
mmjQuery("#mmform-container1478628143 .postalsamechk").click(function(){if(mmjQuery(this).prop('checked')){mmjQuery("#mmform-container1478628143 div[id^='containermssys_postal_']").hide();}else{mmjQuery("#mmform-container1478628143 div[id^='containermssys_postal_']").show();}
setHeight(0);});if(mmjQuery("#mmform-container1478628143 .billsamechk").length>0){if(mmjQuery("#mmform-container1478628143 .billsamechk").is(":checked")){mmjQuery("#mmform-container1478628143 div[id^='containermssys_bill_']").hide();}}
mmjQuery("#mmform-container1478628143 .billsamechk").click(function(){if(mmjQuery(this).prop('checked')){mmjQuery("#mmform-container1478628143 div[id^='containermssys_bill_']").hide();}else{mmjQuery("#mmform-container1478628143 div[id^='containermssys_bill_']").show();}
setHeight(0);});mmjQuery("#mssysform1051301478628143").submit(function(event){if(submitProgress){event.preventDefault();return false;}
error=false;emailuniquefail=false;submitProgress=true;mmjQuery("#mmform-container1478628143 .error-container").hide();mmjQuery("#mmform-container1478628143 .error-field").removeClass('error-field');if(mmjQuery("#mmform-container1478628143 .submitbutton img").length==0){mmjQuery("#mmform-container1478628143 .submitbutton").html("Feldolgozás");}
if(mmjQuery("#mmform-container1478628143 .postalsamechk").prop('checked')&&mmjQuery("#mmform-container1478628143 input[name='shipping_method']:checked").attr("osm_shipping_methods")!='pickpackpont'&&mmjQuery("#mmform-container1478628143 input[name='shipping_method']:checked").attr("osm_shipping_methods")!='shipping_glspont'&&mmjQuery("#mmform-container1478628143 input[name='shipping_method']:checked").attr("osm_shipping_methods")!='mplpont'){mmjQuery("#mmform-container1478628143 #mssys_postal_company").val(mmjQuery("#mmform-container1478628143 #mssys_bill_company").val());mmjQuery("#mmform-container1478628143 #mssys_postal_country").val(mmjQuery("#mmform-container1478628143 #mssys_bill_country option:selected").val());mmjQuery("#mmform-container1478628143 #mssys_postal_zip").val(mmjQuery("#mmform-container1478628143 #mssys_bill_zip").val());mmjQuery("#mmform-container1478628143 #mssys_postal_city").val(mmjQuery("#mmform-container1478628143 #mssys_bill_city").val());mmjQuery("#mmform-container1478628143 #mssys_postal_address").val(mmjQuery("#mmform-container1478628143 #mssys_bill_address").val());mmjQuery("#mmform-container1478628143 #mssys_postal_state").val(mmjQuery("#mmform-container1478628143 #mssys_bill_state").val());}
if(mmjQuery("#mmform-container1478628143 .billsamechk").prop('checked')){mmjQuery("#mmform-container1478628143 #mssys_bill_company").val(mmjQuery("#mmform-container1478628143 #mssys_postal_company").val());mmjQuery("#mmform-container1478628143 #mssys_bill_country").val(mmjQuery("#mmform-container1478628143 #mssys_postal_country option:selected").val());mmjQuery("#mmform-container1478628143 #mssys_bill_zip").val(mmjQuery("#mmform-container1478628143 #mssys_postal_zip").val());mmjQuery("#mmform-container1478628143 #mssys_bill_city").val(mmjQuery("#mmform-container1478628143 #mssys_postal_city").val());mmjQuery("#mmform-container1478628143 #mssys_bill_address").val(mmjQuery("#mmform-container1478628143 #mssys_postal_address").val());mmjQuery("#mmform-container1478628143 #mssys_bill_state").val(mmjQuery("#mmform-container1478628143 #mssys_postal_state").val());}
mmjQuery('input[type="file"]').each(function(){var errormsg='';if(!checkExtension(mmjQuery(this).val())){errormsg="A feltöltendő fájl kiterjesztése nem engedélyezett.";error=true;mmjQuery(this).focus();}
if(errormsg!=''){alert(errormsg);}});if(!emailuniquecheck){if(mmjQuery("#mmform-container1478628143 #containeremail input[name='email']").val()!=''){mmjQuery.ajax({type:"GET",url:"https://sw.marketingszoftverek.hu/api/check-email-uniqueness-json.php",data:{mssys_formid:'wp7l3HEQ4u0vyR8DbWHvwKZb2hfIFoQx',email:mmjQuery("#mmform-container1478628143 input[name='email']").val()},cache:false,dataType:"jsonp",jsonp:'jsonp_callback',async:false,success:function(msg){if(msg.response=='1'){mmjQuery("#mmform-container1478628143 #containeremail .error-container").show().html('Ezzel az email címmel már feliratkozott korábban!');mmjQuery("#mmform-container1478628143 .submitbutton").removeClass('mm-submit-disabled');mmjQuery("#mmform-container1478628143 .submitbutton").html("Feliratkozom");emailuniquefail=true;submitProgress=false;mmjQuery("#mmform-container1478628143 input[name='email']").focus();}else{if(!error){emailuniquecheck=true;emailuniquefail=false;submitProgress=false;mmjQuery("#mssysform1051301478628143").trigger("submit");mmjQuery("#mmform-container1478628143 #containeremail .error-container").hide();}else{emailuniquecheck=false;mmjQuery("#mmform-container1478628143 input[name='email']").focus();}}}});event.preventDefault();}}
if(emailuniquefail){mmjQuery("#mmform-container1478628143 #containeremail .error-container").show();mmjQuery("#mmform-container1478628143 input[name='email']").addClass('error-field');error=true;}
if(!checkMail(mmjQuery("#mmform-container1478628143 input[name='email']").val())){mmjQuery("#mmform-container1478628143 #containeremail .error-container").show();mmjQuery("#mmform-container1478628143 input[name='email']").addClass('error-field').focus();error=true;}
setHeight(0);if(error){submitProgress=false;mmjQuery("#mmform-container1478628143 .submitbutton").removeClass('mm-submit-disabled');if(mmjQuery("#mmform-container1478628143 .submitbutton img").length==0){mmjQuery("#mmform-container1478628143 .submitbutton").html("Feliratkozom");}
return false;}else{messaging.postMessage({setmmcookie:1},parent_url,parent);return true;}});if(document.charset!=undefined){mmjQuery('#mssys-character-encoding').val(document.charset);}else if(document.characterSet!=''){mmjQuery('#mssys-character-encoding').val(document.characterSet);}
mmjQuery(".prodqty, .shippingmethodradio,.prodchk,input[name='prod_id']").trigger('change');setHeight(0);setTimeout(function(){setHeight(0)},1000);mmUtility.saveUtmParams();});mmjQuery.getDocHeight=function(){return Math.max(mmjQuery(document).height(),mmjQuery(window).height(),document.documentElement.clientHeight);};function mmNumberFormat(number,decimals,dec_point,thousands_sep){var n=number,c=isNaN(decimals=Math.abs(decimals))?2:decimals;var d=dec_point==undefined?",":dec_point;var t=thousands_sep==undefined?".":thousands_sep,s=n<0?"-":"";var i=parseInt(n=Math.abs(+n||0).toFixed(c))+"",j=(j=i.length)>3?j%3:0;return s+(j?i.substr(0,j)+t:"")+i.substr(j).replace(/(\d{3})(?=\d)/g,""+t)+(c?d+Math.abs(n-i).toFixed(c).slice(2):"");}
function isNumber(n){return!isNaN(parseFloat(n))&&isFinite(n);}